# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build"
  desc "Build without code sign. Just to see if the build is working"
  lane :build do |options|
    gym(
      scheme: "ReactNativeSemaphore",
      skip_package_ipa: true,
      skip_archive: true,
      silent: true,
      clean: true
    )
  end
end
